#!/usr/bin/env bash
set -x
#set -e
export PATH=".:$PATH"
mkdir -p lists || exit
rm-dot <tlds.txt | while read TLD; do
	tmp="`mktemp --tmpdir=/dev/shm`"
	output_file="lists/$TLD.txt"
	list-domains zonefiles/*$TLD*.txt* | rm-dot >$tmp
	if [ -s $tmp ]; then
		mv -f -- $tmp "$output_file"
	else
		rm -f -- $tmp
	fi
done

