#!/usr/bin/env bash
#set -e
export PATH=".:$PATH"
mkdir -p titles || exit
rm-dot <tlds.txt | while read TLD; do
	tmp="`mktemp --tmpdir=/dev/shm`"
	file="titles/$TLD.txt"
	list-domains ./zonefiles/*$TLD*.txt \
		| get-html-title >"$tmp"
	if [ -s "$tmp" ]; then
		mv -f -- "$tmp" "$file"
	else
		rm -f -- "$tmp"
	fi
done

